#CAMEL PROPERTIES
camel:
  component:
    kafka:
      brokers: rusagro-zhir.tengry.com:9092, rusagro-zhir.tengry.com:9093, rusagro-zhir.tengry.com:9094
      auto-offset-reset: earliest
      client-id: clientValentina
      groupId: groupValentina

#SPRING PROPERTIES
  #spring:
    # kafka:
    #  bootstrap-servers: rusagro-zhir.tengry.com:9092, rusagro-zhir.tengry.com:9093, rusagro-zhir.tengry.com:9094
        #  producer:
        #retries: 0
        #acks: all
        #    key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #   value-serializer: org.apache.kafka.common.serialization.StringSerializer
        #  consumer:
        #     group-id: valentina
        #    auto-offset-reset: earliest
        #     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    #    value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.memorynotfound: DEBUG